windowrule = opacity 1 1, match:class .*



windowrule = workspace 3 silent, match:class ^(discord)$
windowrule = workspace 10, match:class (?i)^(spotify)$
windowrule = workspace name:Mail silent, match:class org.mozilla.Thunderbird
